# Generated by Django 5.2.6 on 2025-10-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(max_length=50, unique=True)),
                ('transport', models.CharField(blank=True, max_length=20, null=True)),
                ('line', models.CharField(blank=True, max_length=50, null=True)),
                ('station', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('item_name', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('is_received', models.BooleanField(default=False)),
                ('registered_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('storage_location', models.CharField(blank=True, max_length=200, null=True)),
                ('registrar_id', models.CharField(blank=True, max_length=100, null=True)),
                ('pickup_company_location', models.CharField(blank=True, max_length=200, null=True)),
                ('views', models.IntegerField(default=0)),
            ],
        ),
    ]
