# Generated by Django 5.2.7 on 2025-10-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lostitem',
            options={'verbose_name': '1. 분실물 정보 (LostItem)', 'verbose_name_plural': '1. 분실물 정보 (LostItems)'},
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='분실물 카테고리'),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='상세 설명'),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='is_received',
            field=models.BooleanField(default=False, verbose_name='반환 여부'),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='item_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='분실물 ID'),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='item_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='물품 상세명'),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='line',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='노선명'),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='pickup_company_location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='수령 회사/위치'),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='수령일시'),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='registered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='등록일시'),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='registrar_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='등록자 ID'),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='station',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='발견역'),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='처리 상태'),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='storage_location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='보관 위치'),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='transport',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='교통수단'),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='views',
            field=models.IntegerField(default=0, verbose_name='조회수'),
        ),
        migrations.CreateModel(
            name='RidershipDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='날짜')),
                ('line_code', models.CharField(max_length=20, verbose_name='표준 노선 코드')),
                ('station_name_std', models.CharField(max_length=100, verbose_name='표준 역명')),
                ('boardings', models.IntegerField(verbose_name='승차 인원 합계')),
                ('alightings', models.IntegerField(verbose_name='하차 인원 합계')),
                ('total', models.IntegerField(verbose_name='총 이용자 수 (승차+하차)')),
            ],
            options={
                'verbose_name': '2-2. 일별 승하차 인원 (RidershipDaily)',
                'verbose_name_plural': '2-2. 일별 승하차 인원 (RidershipDailies)',
                'unique_together': {('date', 'line_code', 'station_name_std')},
            },
        ),
        migrations.CreateModel(
            name='StationDict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name_raw', models.CharField(help_text='데이터 원본에 기록된 역 이름', max_length=100, verbose_name='원천 역명 (OA-12251)')),
                ('station_name_std', models.CharField(db_index=True, help_text='괄호 제거 후 통일된 분석용 역 이름', max_length=100, verbose_name='표준 역명')),
                ('line_code', models.CharField(db_index=True, help_text='LINE1, LINE2 등', max_length=20, verbose_name='표준 노선 코드')),
                ('is_transfer', models.BooleanField(default=False, help_text='2개 이상의 노선이 교차하는 역', verbose_name='환승역 여부')),
            ],
            options={
                'verbose_name': '2-1. 역 표준화 딕셔너리 (StationDict)',
                'verbose_name_plural': '2-1. 역 표준화 딕셔너리 (StationDicts)',
                'unique_together': {('station_name_raw', 'line_code')},
            },
        ),
        migrations.CreateModel(
            name='WeatherDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True, verbose_name='날짜')),
                ('city_code', models.CharField(default='SEOUL', max_length=50, verbose_name='도시 코드')),
                ('is_rainy', models.BooleanField(default=False, help_text='강수량이 0 이상이면 True', verbose_name='강수 여부')),
                ('rain_mm', models.FloatField(default=0.0, verbose_name='일 강수량 (mm)')),
                ('avg_temp', models.FloatField(blank=True, null=True, verbose_name='평균 기온 (C)')),
            ],
            options={
                'verbose_name': '3. 일별 날씨 정보 (WeatherDaily)',
                'verbose_name_plural': '3. 일별 날씨 정보 (WeatherDailies)',
                'unique_together': {('date', 'city_code')},
            },
        ),
    ]
