# Generated by Django 5.2.7 on 2025-10-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_lostitem_options_alter_lostitem_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RainImpactReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_code', models.CharField(max_length=10, verbose_name='노선 코드')),
                ('station_name_std', models.CharField(db_index=True, max_length=50, verbose_name='표준 역명')),
                ('rain_impact_index', models.FloatField(verbose_name='비 효과 지수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시각')),
            ],
            options={
                'verbose_name': '비 영향 보고서',
                'verbose_name_plural': '비 영향 보고서',
                'unique_together': {('line_code', 'station_name_std')},
            },
        ),
    ]
