# Generated by Django 5.2.7 on 2025-10-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rainimpactreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdaily',
            name='date',
            field=models.DateField(db_index=True, verbose_name='날짜'),
        ),
    ]
