# Generated by Django 5.2.7 on 2025-12-06 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_weatherdaily_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='날짜')),
                ('line_no', models.CharField(max_length=50, verbose_name='노선 아이디')),
                ('stops_id', models.CharField(max_length=50, verbose_name='정류장 아이디')),
                ('ride_on', models.IntegerField(verbose_name='승차 인원')),
                ('ride_off', models.IntegerField(verbose_name='하차 인원')),
            ],
        ),
    ]
