# Generated by Django 5.2.7 on 2025-12-06 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_busdaily'),
    ]

    operations = [
        migrations.RenameField(
            model_name='busdaily',
            old_name='line_no',
            new_name='line_id',
        ),
    ]
