# Generated by Django 5.2.7 on 2025-12-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_line_no_busdaily_line_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busdaily',
            name='line_id',
            field=models.CharField(max_length=50, verbose_name='노선 번호'),
        ),
    ]
